openapi: 3.0.0
info:
  title: Спецификация запросов для API сайта "Шесть городов"
  description: |-
    * Пути запросов и компоненты для работы с API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: rentaloffers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.
paths:

  # Предложения по аренде
  /offers:
    get:
      tags:
        - rentaloffers
      summary: Получение списка предложений по аренде
      parameters: [ $ref: '#/components/parameters/limit' ]
      responses:
        "200":
          description: Список предложений по аренде.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'
    post:
      tags:
        - rentaloffers
      summary: Создание нового предложения
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
        required: true
      responses:
        "201":
          description: Предложение создано.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "409":
          description: Предложение уже существует.
  /offers/new:
    get:
      tags:
        - rentaloffers
      summary: Получение списка предложений по аренде
      responses:
        "200":
          description: Список предложений по аренде.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'
  /offers/hot:
    get:
      tags:
        - rentaloffers
      summary: Получение списка предложений по аренде
      responses:
        "200":
          description: Список предложений по аренде.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'
  /offers/premium/{city}:
    parameters: [ $ref: '#/components/parameters/city' ]
    get:
      tags:
        - rentaloffers
      summary: Получение списка предложений по аренде
      responses:
        "200":
          description: Список предложений по аренде.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'
  /offers/{id}:
    parameters: [ $ref: '#/components/parameters/id' ]
    get:
      tags:
        - rentaloffers
      summary: Получение детальной информации о предложении
      responses:
        "201":
          description: Информация о предложении получена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "404":
          description: Такого предложения не существует.
    put:
      tags:
        - rentaloffers
      summary: Редактирование предложения
      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateOffer'
        required: true
      responses:
        "201":
          description: Предложение обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "404":
          description: Такого предложения не существует.
    delete:
      tags:
        - rentaloffers
      summary: Удаление предложения
      responses:
        "201":
          description: Предложение удалено.
        "404":
          description: Такого предложения не существует.

  # Комментарии
  /comments:
    post:
      tags:
        - comments
      summary: Добавление комментария для предложения
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
        required: true
      responses:
        "201":
          description: Комментарий создан.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        "404":
          description: Такого предложения не существует.
  /offers/{id}/comments:
    parameters: [ $ref: '#/components/parameters/id' ]
    get:
      tags:
        - comments
      summary: Получение списка комментариев для предложения
      responses:
        "201":
          description: Комментарии получены.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'
        "404":
          description: Такого предложения не существует.

  # Пользователи
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.
      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь с таким email уже существует.
  /users/login:
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      requestBody:
        description: Информация для авторизации пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUser'
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
        "404":
          description: Такого пользователя не существует.
  /users/{id}/avatar:
    parameters: [ $ref: '#/components/parameters/id' ]
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
        "404":
          description: Такого пользователя не существует.

components:
  parameters:

    # Параметры запросов
    limit:
      name: 'limit'
      description: 'Изменяет количество элементов в ответе'
      in: 'query'
      schema:
        type: number
    city:
      name: 'city'
      description: 'Город, в котором нужно искать премиум-предложения'
      in: 'query'
      schema:
        type: string
    id:
      name: 'id'
      in: path
      required: true
      schema:
        type: string
  schemas:

    # Вспомогательные схемы
    photosArray:
      type: array
      items:
        type: string
        example: "itemImage.png"
    featuresArray:
      type: array
      items:
        type: string
      example: ["Breakfast", "Air conditioning", "Laptop friendly workspace", "Baby seat", "Washer", "Towels", "Fridge"]

    # Основные схемы для запросов
    offerPreview:
      type: object
      properties:
        price:
          type: number
          example: 420
        name:
          type: string
          example: Small Beach House
        type:
          type: string
          example: house
        isFavorite:
          type: boolean
          example: false
        createdDate:
          type: string
          example: "2023-01-10T01:07:21.762Z"
        city:
          type: string
          example: Cologne
        previewImage:
          type: string
          example: photo.jpg
        isPremium:
          type: boolean
          example: true
        rating:
          type: number
          example: 2.5
        commentCount:
          type: number
          example: 3
        user:
          $ref: '#/components/schemas/user'
    offer:
      type: object
      properties:
        price:
          type: number
          example: 420
        name:
          type: string
          example: Small Beach House
        type:
          type: string
          example: house
        isFavorite:
          type: boolean
          example: false
        createdDate:
          type: string
          example: "2023-01-10T01:07:21.762Z"
        city:
          type: string
          example: Cologne
        previewImage:
          type: string
          example: photo.jpg
        isPremium:
          type: boolean
          example: true
        rating:
          type: number
          example: 2.5
        commentCount:
          type: number
          example: 3
        user:
          $ref: '#/components/schemas/user'
        description:
          type: number
          example: 3
        photos:
          $ref: '#/components/schemas/photosArray'
        rooms:
          type: number
          example: 3
        guests:
          type: number
          example: 3
        features:
          $ref: '#/components/schemas/featuresArray'
        coordinates:
          type: array
          example: [52.6, 25.12]
    offers:
      type: array
      items:
        $ref: '#/components/schemas/offerPreview'
    createOffer:
      type: object
      properties:
        price:
          type: number
          example: 420
        name:
          type: string
          example: Small Beach House
        type:
          type: string
          example: house
        isFavorite:
          type: boolean
          example: false
        createdDate:
          type: string
          example: "2023-01-10T01:07:21.762Z"
        city:
          type: string
          example: Cologne
        previewImage:
          type: string
          example: photo.jpg
        isPremium:
          type: boolean
          example: true
        rating:
          type: number
          example: 2.5
        commentCount:
          type: number
          example: 3
        user:
          $ref: '#/components/schemas/user'
        description:
          type: number
          example: 3
        photos:
          $ref: '#/components/schemas/photosArray'
        rooms:
          type: number
          example: 3
        guests:
          type: number
          example: 3
        features:
          $ref: '#/components/schemas/featuresArray'
        coordinates:
          type: array
          example: [52.6, 25.12]
    updateOffer:
      type: object
      properties:
      $ref: '#/components/schemas/createOffer'

    comment:
      type: object
      properties:
        id:
          type: string
          example: a313c3d6a15ac1022c6115ba
        text:
          type: string
          example: Looks very good, but has problems with cleanup
        rating:
          type: number
          example: 3
        createdDate:
          type: string
          example: 2021-10-10T10:10:10.000Z
        user:
          $ref: '#/components/schemas/user'
    comments:
      type: array
      items:
        $ref: '#/components/schemas/comment'
    createComment:
      type: object
      properties:
        text:
          type: string
          example: 27user@pm.me
        offerId:
          type: string
          example: a313c3d6a15ac1022c6115ba
        rating:
          type: number
          example: 3

    user:
      type: object
      properties:
        name:
          type: string
          example: Alexander
        email:
          type: string
          example: 27user@pm.me
        avatar:
          type: string
          example: avatar.png
        type:
          type: string
          example: обычный
        favoriteOffers:
          type: array
          example: [a313c3d6a15ac1022c6115ba, b512c3d6a15ac1022c6641aa]
    createUser:
      type: object
      properties:
        email:
          type: string
          example: 27user@pm.me
        name:
          type: string
          example: Alexander
        password:
          type: string
          example: "*userpassword2021"
    loginUser:
      type: object
      properties:
        email:
          type: string
          example: 27user@pm.me
        password:
          type: string
          example: "*userpassword2021"
    token:
      type: object
      properties:
        email:
          type: string
          example: 27user@pm.me
        token:
          type: string
          example: 27user@pm.me
